"""Reconcile the observable contracts against the CLOSURE-generated manifests.

Scope, set when the ``closure_*`` packages moved into this repo: **only the tests
that read closure-generated data live here.** The contract loader, the bibliography,
the NNPDF4.0 roster and the schema validator are PIXEL's artifacts, tested by
``pixel/tests/test_observable_contracts.py``; this file does not re-test them.

The file was originally copied whole from that pixel module on 2026-08-16, header
and all, and its own header said so: *"The remaining tests here duplicate pixel ones;
trim if that becomes a maintenance problem."* It became one. Ten of the thirteen
tests were verbatim duplicates, and one of them --
``test_data_reference_bib_is_valid_and_deduplicated`` -- failed here for a reason
that says exactly why they do not belong: it shells out to
``scripts/update_data_references.py`` and reads ``nnpdf40_dis_dy_roster.yaml``,
neither of which came across the move, because neither is a closure artifact. The
duplicates are dropped rather than repaired; pixel still runs every one of them.

What remains are the three that genuinely exercise this repo: each reads
``closure_*/data/truthQ_mc/manifest.json``, produced by that suite's own
``generate.py``, and reconciles it against the contract table. They are the only
gate on generation actually emitting what the contracts declare.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import numpy as np
import pytest

from pixel.data.contracts import (
    annotate_manifest,
    contract_index,
    load_observable_contracts,
    matching_contracts,
)


ROOT = Path(__file__).resolve().parents[1]


def _manifest(suite: str, *, sections: tuple[str, ...] = ()) -> dict:
    """Load one suite's generated closure manifest, skipping if it is incomplete.

    ``suite`` is ``"closure_JAM_truth"`` or ``"closure_NNPDF_truth"``; the file read is
    ``<suite>/data/truthQ_mc/manifest.json``, produced by that suite's own
    ``generate.py``, not regenerated by this call. A ``generate.py`` change is only
    visible to the tests below once the manifest has been regenerated.

    ``sections`` names the record lists the caller actually indexes. Each is checked
    for presence and ``pytest.skip``ed **by name** if absent, because ``generate.py``
    writes this file *twice* for a full suite: once at ``generate.py:713`` carrying
    ``lattice``/``exp`` only, then again at ``generate.py:856`` after the Drell-Yan
    block adds ``dy``. A member whose generation stopped between those two writes
    leaves a manifest that is valid JSON, correct as far as it goes, and silently
    missing ``dy`` -- which reached the callers below as a bare ``KeyError: 'dy'``
    rather than as the "this member was never finished" that it actually is.

    Deliberately narrow, for the reason recorded on the sibling skip at
    ``test_closure_pseudoitd_matching.py:762``: a blanket skip would also swallow a
    ``generate.py`` regression that stopped emitting a section on purpose. Only the
    sections a caller names are gated, so each test keeps running on every section
    the on-disk data can support -- ``test_lattice_selected_rows_...`` still
    exercises ``lattice`` against exactly the partial members that make the two
    ``dy`` readers skip.
    """
    path = ROOT / suite / "data" / "truthQ_mc" / "manifest.json"
    if not path.exists():
        pytest.skip(f"{suite} truthQ_mc was not generated in this checkout")
    manifest = json.loads(path.read_text(encoding="utf-8"))
    missing = [name for name in sections if name not in manifest]
    if missing:
        pytest.skip(
            f"{suite} truthQ_mc manifest is missing {missing}: generation stopped "
            f"before that section was written. Regenerate the member with "
            f"`python -m {suite}.generate --Q mc` to re-enable this test."
        )
    return manifest


def test_current_full_closure_manifest_has_exact_contract_and_citations():
    """Every generated lattice/exp/dy record matches exactly one contract, both ways.

    ``set(seen) == expected_ids`` is the real, bidirectional claim: it fails if a
    ``full_closure_modes`` id is declared but never produced by generation, or if
    generation produces a contract-mapped id outside that list. The lattice
    reconciliation (``== 234``, ``all(... == 18)``) is checked against the real
    committed manifest (measured: ``len(manifest["lattice"]) == 234`` over 13
    ensembles), not merely restated from the yaml -- but it is an independently
    hardcoded pin, not a read of ``by_id[id]["selected_rows"]`` the way the next test
    does for ``exp``/``dy``; this file has no lattice equivalent of that
    cross-reference (missing coverage, topic ``data-builders``).

    Two sub-checks are ``W-NEVER`` as written -- see the inline comments below for what
    each would need to change to matter. ``expected_ids == nnpdf_full``'s ids is an
    authoring guard only: the yaml defines ``nnpdf_full.dataset_ids`` as a literal YAML
    alias (``*current_full_ids``) of ``jam_full``'s, so today they are the same list
    object; this can fail only if a future edit splits the alias into two hand-typed,
    diverging lists.
    """
    contracts = load_observable_contracts()
    expected_ids = set(contracts["full_closure_modes"]["jam_full"]["dataset_ids"])
    assert expected_ids == set(
        contracts["full_closure_modes"]["nnpdf_full"]["dataset_ids"]
    )

    for suite in ("closure_JAM_truth", "closure_NNPDF_truth"):
        manifest = _manifest(suite, sections=("lattice", "exp", "dy"))
        annotated = annotate_manifest(manifest, contracts=contracts)
        seen = Counter()
        for section in ("lattice", "exp", "dy"):
            for original, record in zip(manifest[section], annotated[section], strict=True):
                matches = matching_contracts(contracts, section, original)
                # W-NEVER: annotate_manifest (contracts.py:286-291) already made this
                # identical, deterministic call on the same record content two lines up
                # and raises ContractError if it disagrees -- that raise path itself has
                # no test anywhere (see missing coverage, topic data-builders).
                assert len(matches) == 1
                seen[record["contract_id"]] += 1
                # Real: covers every classification here, not just "physics" (contrast
                # the sibling completeness test above).
                assert record["citation_keys"]
                # W-NEVER: annotate_manifest (contracts.py:293-306) writes both sides
                # from the identical contract[...] expression with no branch between
                # them, and the real manifests carry no pre-existing "provenance" key
                # to diverge from (checked directly: False for lattice/exp/dy record 0).
                assert record["provenance"]["citation_keys"] == record["citation_keys"]
                assert record["provenance"]["contract_id"] == record["contract_id"]
        # Real and bidirectional -- see the docstring above.
        assert set(seen) == expected_ids
        # 234 = 13 lattice ensembles x 18 records each; measured against the real
        # manifest, not merely restated from the yaml's own selected_rows: 18 fields.
        assert sum(seen[dataset_id] for dataset_id in expected_ids if dataset_id.startswith("lattice.")) == 234
        assert all(
            seen[dataset_id] == 18
            for dataset_id in expected_ids
            if dataset_id.startswith("lattice.")
        )


def test_selected_point_counts_reconcile_with_generated_full_manifest():
    """``exp``/``dy`` contract ``selected_rows`` equals the real generated point count.

    ``point_count`` comes from the generated closure data itself -- ``len(mean)`` for a
    bilinear DY record, else an on-disk table read with ``np.loadtxt`` -- not from the
    yaml, so a cuts change that silently retains a different row count than
    ``observable_contracts.yaml`` declares would be caught. Restricted to
    ``("exp", "dy")``; ``"lattice"`` has no equivalent check anywhere in this file (the
    sibling test above pins the lattice count independently instead of reading this same
    ``selected_rows`` field -- missing coverage, topic ``data-builders``).

    ``matching_contracts(...)`` is now checked for ``len(matches) == 1`` before
    indexing, matching the sibling test's explicit check on the same kind of call.
    Previously it took ``matches[0]`` unconditionally, so an ambiguous selector --
    two contracts matching the same ``exp``/``dy`` record -- silently picked the
    first and this test went on comparing ``point_count`` against whichever
    ``selected_rows`` happened to sort first, which for a correct row count would
    still pass. Not a live risk against the current file (the sibling test proves
    uniqueness for this same manifest), but this test alone did not establish it,
    and after a selector edit the two tests can disagree about which manifest they
    cover. Measured on the committed manifest: every one of the ``exp``/``dy``
    records matches exactly one contract, so the new assertion is satisfied with
    no slack rather than being vacuously true.
    """
    contracts = load_observable_contracts()
    by_id = contract_index(contracts)
    manifest = _manifest("closure_JAM_truth", sections=("exp", "dy"))
    for section in ("exp", "dy"):
        for record in manifest[section]:
            matches = matching_contracts(contracts, section, record)
            # An ambiguous selector must fail loudly rather than silently take
            # matches[0] -- symmetry with the sibling test above.
            assert len(matches) == 1, (section, record.get("file"), len(matches))
            contract = matches[0]
            if "mean" in record:
                point_count = len(record["mean"])
            else:
                data_path = (
                    ROOT / "closure_JAM_truth" / "data" / "truthQ_mc" / record["file"]
                )
                point_count = np.loadtxt(data_path, ndmin=2).shape[0]
            # Real cross-check: generated data's row count vs. the yaml's own declared
            # selected_rows field for this same contract -- see the docstring above.
            assert point_count == by_id[contract["id"]]["selected_rows"]


def test_lattice_selected_rows_reconcile_with_the_generated_full_manifest():
    """The lattice half of the ``exp``/``dy`` reconciliation, which had no equivalent.

    Oracle ``A3``: the count comes from the committed, generated manifest;
    ``selected_rows`` comes from the yaml.  The sibling completeness test does check
    the lattice totals (``== 234``, ``all(... == 18)``), but against *independently
    hardcoded literals* -- so an edit that moved a lattice contract's
    ``selected_rows`` away from what generation actually emits was caught nowhere in
    this file, which is precisely the drift
    ``test_selected_point_counts_reconcile_with_generated_full_manifest`` exists to
    catch for ``exp``/``dy``.

    The lattice unit differs from ``exp``/``dy``'s and the assertion follows it: one
    lattice contract covers a whole ensemble, so its ``selected_rows`` (18) is the
    number of *manifest records* selected by that contract, not the row count of any
    one data file.  ``matching_contracts`` is what partitions the records, and
    ``len(matches) == 1`` is asserted first, so an ambiguous ``name_regex`` cannot
    quietly inflate one ensemble's tally by stealing another's records.  Both
    committed suites are checked; the sum is asserted too, so a contract that matched
    nothing would fail here rather than being skipped by an empty ``Counter``.
    """
    contracts = load_observable_contracts()
    by_id = contract_index(contracts)
    lattice_ids = sorted(
        dataset_id for dataset_id in by_id if dataset_id.startswith("lattice.")
    )
    assert lattice_ids, "no lattice contracts in the table; fixture assumption broken"

    for suite in ("closure_JAM_truth", "closure_NNPDF_truth"):
        manifest = _manifest(suite, sections=("lattice",))
        seen = Counter()
        for record in manifest["lattice"]:
            matches = matching_contracts(contracts, "lattice", record)
            assert len(matches) == 1
            seen[str(matches[0]["id"])] += 1
        for dataset_id in lattice_ids:
            assert seen[dataset_id] == by_id[dataset_id]["selected_rows"]
        assert sum(seen.values()) == sum(
            by_id[dataset_id]["selected_rows"] for dataset_id in lattice_ids
        )
