"""Copied from pixel/tests/test_observable_contracts.py 2026-08-16.

Kept whole (helpers and all) so the three tests that reconcile the observable
contracts against the CLOSURE-generated manifests keep working:
  test_current_full_closure_manifest_has_exact_contract_and_citations
  test_selected_point_counts_reconcile_with_generated_full_manifest
  test_lattice_selected_rows_reconcile_with_the_generated_full_manifest
Those three were removed from the pixel copy -- they read
``closure_*/data/truthQ_mc/manifest.json``, which pixel will not have once the
closure packages move.  The remaining tests here duplicate pixel ones; trim if
that becomes a maintenance problem.
"""

"""Scientific roster and paper-provenance gates for full closure.

Exercises ``pixel.data.contracts`` directly (no re-export shim):
``load_observable_contracts``, ``contract_index``, ``matching_contracts``,
``annotate_manifest``, and ``closure_extension_roster``, which together make
``observable_contracts.yaml`` (52 dataset records, ~50 KB) authoritative over both the
closure generators (``closure_JAM_truth/config.py``'s ``_CONTRACT_SELECTION =
full_closure_selection("jam_full")``) and their committed output manifests.

Two oracle layers, of different strength:

* ``load_observable_contracts()`` runs a JSON Schema
  (``schemas/pixel.observable_contracts.v1.json``) and then
  ``validate_observable_contracts``'s hand-written cross-field checks *before* any test
  in this file sees the contract dict. A fair fraction of the assertions below duplicate
  an invariant that upstream validation, or the schema itself, already enforced on the
  very same call -- each is flagged in place with what it would actually take to fail.
  That upstream validation is real, but it is not this file's own contribution, and it
  is itself unverified: every ``ContractError`` branch in
  ``validate_observable_contracts`` has zero negative-path test coverage anywhere in the
  suite (see ``tests/TEST_EXPLANATION.md``).
* ``data_reference.bib`` is parsed independently with ``pybtex``
  (``test_data_reference_bib_is_valid_and_deduplicated``) and cross-checked again, out
  of process, by ``python scripts/update_data_references.py --check``. The subprocess
  is a second implementation of the citation-resolution logic, but it loads the same
  committed ``observable_contracts.yaml`` through the same
  ``load_observable_contracts()`` -- independent in code, not in the underlying data or
  the loader.

``pybtex`` (module scope, line 12) is a *core* dependency (``pyproject.toml``
``dependencies``, not ``[project.optional-dependencies]``), alongside
``PyYAML``/``jsonschema``: BibTeX provenance is parsed rather than regex-checked so a
malformed or duplicate reference cannot silently enter a closure run. Unlike an
extras-gated import (``tests/test_mcp_server.py``'s unconditional ``import anyio`` fails
collection whenever the optional ``mcp`` extra is absent, leaving that file's own skip
guard unreachable), a plain ``pip install .`` always provides ``pybtex`` -- confirmed
importable in this repo's ``venv`` (0.26.1) -- so this module-level import is not a
latent collection-failure risk here.

The two full-closure manifests this file reconciles against (``closure_JAM_truth``/
``closure_NNPDF_truth/data/truthQ_mc/manifest.json``, ~1.27 MB each) are committed,
generated snapshots: a ``generate.py`` change to dataset selection is only visible here
once the manifest has been regenerated and recommitted. The nearer thing to a "tighter,
production-size" reference is ``scripts/update_data_references.py --check``, which
additionally reconciles ``nnpdf40_dis_dy_roster.yaml`` (see
``tests/test_nnpdf40_roster.py``, which this file does not otherwise touch).
"""

from __future__ import annotations

import copy
import hashlib
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

import numpy as np
import pytest
import yaml
from pybtex.database import parse_file

from pixel.data.contracts import (
    ContractError,
    annotate_manifest,
    closure_extension_roster,
    contract_artifact_provenance,
    contract_index,
    load_observable_contracts,
    matching_contracts,
    validate_observable_contracts,
)


ROOT = Path(__file__).resolve().parents[1]


def _manifest(suite: str) -> dict:
    """Load one suite's committed, generated closure manifest.

    ``suite`` is ``"closure_JAM_truth"`` or ``"closure_NNPDF_truth"``; the file read is
    ``<suite>/data/truthQ_mc/manifest.json``, produced by that suite's own
    ``generate.py`` and committed to the repo, not regenerated by this call. A
    ``generate.py`` change is only visible to the tests below once the manifest has
    been regenerated and recommitted.
    """
    path = ROOT / suite / "data" / "truthQ_mc" / "manifest.json"
    return json.loads(path.read_text(encoding="utf-8"))


def test_observable_contracts_are_complete():
    """Truth-law policy is real; most of the physics-metadata block is not.

    ``truth_laws`` checks (``kind``, ``member``, no ``replica_ensemble_mean`` anywhere
    in the values) are the only place enforcing "one representable PDF, not an ensemble
    second moment" (see ``pixel/data/contracts.py``'s module docstring) on
    ``jam_full``/``nnpdf_full``: the schema's ``kind`` enum also allows
    ``"fixed_gp_draw"`` and does not pin ``member``, so nothing else in the loader would
    catch either drifting.

    The four remaining per-physics-record checks are bundled with one real one and
    three that are ``W-NEVER``: ``physics_required``/``operator_required`` are, by
    direct comparison, exactly the schema's ``observable.required``/
    ``operator.required`` sets, and ``evidence["local"]``/``["paper"]`` truthy are
    guaranteed by the schema's ``minItems``/``minLength`` -- all four already apply to
    *every* dataset, physics or not, inside ``load_observable_contracts()`` two lines
    up, so a dataset missing any of them never reaches this loop at all. Only
    ``citation_keys`` truthy is additional: the schema has no ``minItems`` on it, so
    ``[]`` is schema-legal and this is the one check that would actually catch a
    physics dataset losing its citations.
    """
    contracts = load_observable_contracts()
    records = contract_index(contracts)

    # W-NEVER: contract_index (contracts.py:153-155) keys on the identical str(id)
    # that validate_observable_contracts (contracts.py:85-87) already deduplicated
    # on, inside load_observable_contracts() one line up -- a disagreement here
    # would already have raised ContractError. Measured on the real file: 52 == 52.
    assert len(records) == len(contracts["datasets"])
    # Real: schema's `kind` enum also permits "fixed_gp_draw"; nothing else pins this.
    assert {law["kind"] for law in contracts["truth_laws"].values()} == {
        "fixed_lhapdf_member"
    }
    # Real: schema only requires member to be a non-negative int or null, not exactly 1.
    assert all(law["member"] == 1 for law in contracts["truth_laws"].values())
    # Real: guards the "not an ensemble second moment" policy the schema cannot express.
    assert not any(
        "replica_ensemble_mean" in str(value)
        for law in contracts["truth_laws"].values()
        for value in law.values()
    )

    # Equals schema $defs.observable.required exactly (verified) -- see docstring above.
    physics_required = {
        "quantity",
        "units",
        "reaction",
        "beam",
        "target",
        "binning",
        "fiducial",
        "qed_fsr",
    }
    # Equals schema $defs.operator.required exactly (verified) -- see docstring above.
    operator_required = {
        "kind",
        "perturbative_order",
        "scale",
        "flavour_scheme",
        "nuclear",
        "returns",
    }
    for record in records.values():
        if record["classification"] != "physics":
            continue
        # W-NEVER: schema requires exactly physics_required on every dataset's
        # "observable", not just physics ones -- already enforced before this loop runs.
        assert physics_required <= set(record["observable"])
        # W-NEVER: schema requires exactly operator_required on every dataset's
        # "operator", not just physics ones -- already enforced before this loop runs.
        assert operator_required <= set(record["operator"])
        # Real: schema has no minItems on citation_keys, so [] is schema-legal here.
        assert record["citation_keys"]
        # W-NEVER: schema's evidence.local has minItems: 1 for every dataset already.
        assert record["evidence"]["local"]
        # W-NEVER: schema's evidence.paper has minLength: 1 for every dataset already.
        assert record["evidence"]["paper"]


def test_current_full_closure_manifest_has_exact_contract_and_citations():
    """Every generated lattice/exp/dy record matches exactly one contract, both ways.

    ``set(seen) == expected_ids`` is the real, bidirectional claim: it fails if a
    ``full_closure_modes`` id is declared but never produced by generation, or if
    generation produces a contract-mapped id outside that list. The lattice
    reconciliation (``== 234``, ``all(... == 18)``) is checked against the real
    committed manifest (measured: ``len(manifest["lattice"]) == 234`` over 13
    ensembles), not merely restated from the yaml -- but it is an independently
    hardcoded pin, not a read of ``by_id[id]["selected_rows"]`` the way the next test
    does for ``exp``/``dy``; this file has no lattice equivalent of that
    cross-reference (missing coverage, topic ``data-builders``).

    Two sub-checks are ``W-NEVER`` as written -- see the inline comments below for what
    each would need to change to matter. ``expected_ids == nnpdf_full``'s ids is an
    authoring guard only: the yaml defines ``nnpdf_full.dataset_ids`` as a literal YAML
    alias (``*current_full_ids``) of ``jam_full``'s, so today they are the same list
    object; this can fail only if a future edit splits the alias into two hand-typed,
    diverging lists.
    """
    contracts = load_observable_contracts()
    expected_ids = set(contracts["full_closure_modes"]["jam_full"]["dataset_ids"])
    assert expected_ids == set(
        contracts["full_closure_modes"]["nnpdf_full"]["dataset_ids"]
    )

    for suite in ("closure_JAM_truth", "closure_NNPDF_truth"):
        manifest = _manifest(suite)
        annotated = annotate_manifest(manifest, contracts=contracts)
        seen = Counter()
        for section in ("lattice", "exp", "dy"):
            for original, record in zip(manifest[section], annotated[section], strict=True):
                matches = matching_contracts(contracts, section, original)
                # W-NEVER: annotate_manifest (contracts.py:286-291) already made this
                # identical, deterministic call on the same record content two lines up
                # and raises ContractError if it disagrees -- that raise path itself has
                # no test anywhere (see missing coverage, topic data-builders).
                assert len(matches) == 1
                seen[record["contract_id"]] += 1
                # Real: covers every classification here, not just "physics" (contrast
                # the sibling completeness test above).
                assert record["citation_keys"]
                # W-NEVER: annotate_manifest (contracts.py:293-306) writes both sides
                # from the identical contract[...] expression with no branch between
                # them, and the real manifests carry no pre-existing "provenance" key
                # to diverge from (checked directly: False for lattice/exp/dy record 0).
                assert record["provenance"]["citation_keys"] == record["citation_keys"]
                assert record["provenance"]["contract_id"] == record["contract_id"]
        # Real and bidirectional -- see the docstring above.
        assert set(seen) == expected_ids
        # 234 = 13 lattice ensembles x 18 records each; measured against the real
        # manifest, not merely restated from the yaml's own selected_rows: 18 fields.
        assert sum(seen[dataset_id] for dataset_id in expected_ids if dataset_id.startswith("lattice.")) == 234
        assert all(
            seen[dataset_id] == 18
            for dataset_id in expected_ids
            if dataset_id.startswith("lattice.")
        )


def test_selected_point_counts_reconcile_with_generated_full_manifest():
    """``exp``/``dy`` contract ``selected_rows`` equals the real generated point count.

    ``point_count`` comes from the generated closure data itself -- ``len(mean)`` for a
    bilinear DY record, else an on-disk table read with ``np.loadtxt`` -- not from the
    yaml, so a cuts change that silently retains a different row count than
    ``observable_contracts.yaml`` declares would be caught. Restricted to
    ``("exp", "dy")``; ``"lattice"`` has no equivalent check anywhere in this file (the
    sibling test above pins the lattice count independently instead of reading this same
    ``selected_rows`` field -- missing coverage, topic ``data-builders``).

    ``matching_contracts(...)`` is now checked for ``len(matches) == 1`` before
    indexing, matching the sibling test's explicit check on the same kind of call.
    Previously it took ``matches[0]`` unconditionally, so an ambiguous selector --
    two contracts matching the same ``exp``/``dy`` record -- silently picked the
    first and this test went on comparing ``point_count`` against whichever
    ``selected_rows`` happened to sort first, which for a correct row count would
    still pass. Not a live risk against the current file (the sibling test proves
    uniqueness for this same manifest), but this test alone did not establish it,
    and after a selector edit the two tests can disagree about which manifest they
    cover. Measured on the committed manifest: every one of the ``exp``/``dy``
    records matches exactly one contract, so the new assertion is satisfied with
    no slack rather than being vacuously true.
    """
    contracts = load_observable_contracts()
    by_id = contract_index(contracts)
    manifest = _manifest("closure_JAM_truth")
    for section in ("exp", "dy"):
        for record in manifest[section]:
            matches = matching_contracts(contracts, section, record)
            # An ambiguous selector must fail loudly rather than silently take
            # matches[0] -- symmetry with the sibling test above.
            assert len(matches) == 1, (section, record.get("file"), len(matches))
            contract = matches[0]
            if "mean" in record:
                point_count = len(record["mean"])
            else:
                data_path = (
                    ROOT / "closure_JAM_truth" / "data" / "truthQ_mc" / record["file"]
                )
                point_count = np.loadtxt(data_path, ndmin=2).shape[0]
            # Real cross-check: generated data's row count vs. the yaml's own declared
            # selected_rows field for this same contract -- see the docstring above.
            assert point_count == by_id[contract["id"]]["selected_rows"]


def test_data_reference_bib_is_valid_and_deduplicated():
    """The committed ``.bib`` file's keys equal the yaml crosswalk's, exactly.

    ``set(bib.entries) == expected`` is the one independent in-process check:
    ``pybtex`` parses ``data_reference.bib`` on its own, sharing no code with
    ``contracts.py``'s YAML/jsonschema loading, so a key added to one file and not
    the other is caught here. ``len(expected) == len({inspire_id, ...})`` is
    ``W-NEVER``: ``load_observable_contracts()`` on the line above already raises inside
    ``validate_observable_contracts`` (contracts.py:65-68) if either citation keys or
    inspire ids repeat among the same papers, so by the time this line runs both counts
    are already provably ``len(papers)`` (measured: 39 == 39 on the real file).

    The subprocess call is the real completeness check -- it additionally reconciles
    ``nnpdf40_dis_dy_roster.yaml`` and verifies each dataset's ``citation_keys`` resolve
    (``validate_bibliography``, ``scripts/update_data_references.py:67-121``), which
    nothing else in this file touches. ``W-COMMON`` caveat, now partly closed: the
    script calls the same ``load_observable_contracts()`` on the same committed file,
    so a loader bug (as opposed to a bibliography-content bug) would pass both there
    and in-process.
    Asserting on stdout content is a coarse black-box pin -- any internal check failing
    prevents that string from printing, but this does not identify which one did.

    **The loader is now off the critical path for the crosswalk itself.** A third
    route reads ``observable_contracts.yaml`` with plain ``yaml.safe_load`` -- no
    ``contracts.py``, no jsonschema, no normalization -- and the citation-key set
    derived that way is compared against the loader's *and* against ``pybtex``'s.
    Any two of the three agreeing while the third differs localizes the fault:
    loader vs. raw yaml isolates ``contracts.py``, raw yaml vs. ``.bib`` isolates
    content drift. That is precisely what the ``W-COMMON`` caveat said was missing,
    since a loader that dropped or rewrote a paper entry previously moved *both*
    sides of the in-process comparison together. It also adds a containment check
    the file had nowhere in-process: every ``citation_keys`` entry any dataset
    references must exist both as a paper and as a ``.bib`` entry. Measured on the
    committed files: 39 papers by all three routes, 25 distinct keys referenced
    across the 52 datasets, all resolving.
    """
    contracts = load_observable_contracts()
    bib = parse_file(str(ROOT / "data_reference.bib"), "bibtex")
    expected = {
        paper["citation_key"] for paper in contracts["bibliography"]["papers"]
    }
    # Real: pybtex is an independent parser -- see the docstring above.
    assert set(bib.entries) == expected
    # W-NEVER: both counts already equal len(papers), guaranteed by
    # validate_observable_contracts before this line runs -- see the docstring above.
    assert len(expected) == len(
        {paper["inspire_id"] for paper in contracts["bibliography"]["papers"]}
    )

    # Third route, with contracts.py on neither side: the raw yaml, parsed by
    # yaml.safe_load alone.  Breaks the W-COMMON tie between this test and the
    # subprocess below, both of which otherwise read the file through the loader.
    raw = yaml.safe_load((ROOT / "observable_contracts.yaml").read_text(encoding="utf-8"))
    raw_keys = {paper["citation_key"] for paper in raw["bibliography"]["papers"]}
    # loader vs. raw yaml: isolates contracts.py from bibliography content.
    assert raw_keys == expected
    # raw yaml vs. the .bib, with the loader out of the picture entirely.
    assert raw_keys == set(bib.entries)
    # Containment: every key any dataset cites must resolve, checked without the
    # loader.  Measured 25 distinct keys across the 52 datasets on the real file.
    referenced = {
        key for dataset in raw["datasets"] for key in dataset.get("citation_keys", ())
    }
    assert referenced, "no dataset cites anything -- fixture is degenerate"
    assert referenced <= raw_keys  # every cited key is a declared paper
    assert referenced <= set(bib.entries)  # ...and resolves in the .bib

    result = subprocess.run(
        [sys.executable, "scripts/update_data_references.py", "--check"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    # Coarse black-box success pin; W-COMMON caveat -- see the docstring above.
    assert "valid, complete, and deduplicated" in result.stdout


def test_w_contracts_use_boson_asymmetry_papers_not_lepton_asymmetry():
    """``w.d0_1001`` cites the W-rapidity paper, not the withdrawn lepton-asymmetry one.

    Oracle D1, hardcoded with recorded provenance: the yaml's own ``gate_evidence`` on
    ``w.d0_1001`` states "not the lepton-asymmetry dataset INSPIRE 1253555" -- a real,
    separately-cited paper in this file's bibliography (``D0:2013xqc``, used by the
    NNPDF4.0 roster), distinct from ``D0:2013lql`` (1268647, the true boson-rapidity
    measurement this dataset actually uses). This guards a specific, documented
    historical mix-up between two similarly-named D0 W-asymmetry measurements, not a
    generic smoke check. ``w.cdf_1000 == [811060]`` is a parallel identity pin without a
    documented alternate-id confusion behind it. Catches: a future edit re-citing either
    W dataset to the wrong INSPIRE record.
    """
    contracts = contract_index(load_observable_contracts())
    assert contracts["w.cdf_1000"]["inspire_ids"] == [811060]
    assert contracts["w.d0_1001"]["inspire_ids"] == [1268647]
    # 1253555 = D0:2013xqc, the lepton-charge-asymmetry measurement -- not this
    # dataset's true boson-rapidity paper D0:2013lql/1268647. See the docstring above.
    assert 1253555 not in {
        inspire_id
        for record in contracts.values()
        for inspire_id in record.get("inspire_ids", ())
    }


def test_full_closure_extension_roster_makes_every_gate_visible():
    """All 22 EW/NNPDF extension candidates stay visible; none is silently selected.

    Demonstrated, not just argued: with the real prefix tuple
    (``"z.", "w.", "dy.e906", "dy.e605", "dis.chorus", "dis.nutev"``),
    ``candidate_source_count`` is 22 and ``selected_source_count`` is 0 for both modes
    (measured directly). Re-running the same candidate/selected logic in a scratch
    script with a widened ``"dy."`` prefix in place of ``"dy.e906"``/``"dy.e605"``
    moves those numbers to 24 and 2 -- it picks up the already-selected
    ``dy.e866_pp``/``dy.e866_pd`` contracts -- so the
    ``excluded``-classification/``drop_reason``/``citation_keys`` checks below are not
    vacuous against a plausible prefix-widening bug. Zero-selected is a fact about
    today's roster, not a structural guarantee the assertions enforce on their own;
    ``selected_source_count``/``selected_row_count``/``selected == []`` all currently
    follow from that fact rather than being independently informative.

    Exercises only the empty-roster branch: no test in this file, or found elsewhere
    in the suite, calls ``annotate_manifest`` on a manifest with a populated
    ``"datasets"`` section, so the annotation path this roster exists to gate (per the
    source docstring: "prevents a future contract promotion from being silently
    ignored by generation") has no test covering what happens once a candidate is
    actually promoted (missing coverage, topic ``data-builders``).
    """
    for mode in ("jam_full", "nnpdf_full"):
        roster = closure_extension_roster(mode)
        # 22 = every dataset id starting with z./w./dy.e906/dy.e605/dis.chorus/
        # dis.nutev; measured directly against the real yaml -- see docstring above.
        assert roster["candidate_source_count"] == 22
        # Currently entailed by `selected == []` below; see the docstring above.
        assert roster["selected_source_count"] == 0
        assert roster["selected_row_count"] == 0
        assert roster["selected"] == []
        # Real: would catch a candidate wrongly promoted without a full_closure_modes
        # entry, or the prefix-widening bug demonstrated in the docstring above.
        assert all(row["classification"] == "reader_only" for row in roster["excluded"])
        assert all(row["drop_reason"] for row in roster["excluded"])
        assert all(row["citation_keys"] for row in roster["excluded"])


# ---------------------------------------------------------------------------
# The guards themselves.
#
# Added 2026-08-13.  Five assertions in this file were found to be unreachable in
# the strict sense: each re-checks an invariant that ``load_observable_contracts()``
# has *already* enforced and raised on, one to five lines earlier.  If the invariant
# were ever violated the loader would raise first, so the test would ERROR during
# setup and the assertion would never execute -- it cannot fail, and it cannot pass
# for a reason either.  Meanwhile the ``raise ContractError`` branches doing the real
# work were reached by no test anywhere.
#
# The fix is the inverse of the usual one: not a better fixture, but a deliberately
# BROKEN one.  Each case below corrupts a deep copy of the committed table in exactly
# one way and asserts the specific error.  Corrupting a copy of the real table rather
# than hand-building a minimal dict matters -- a minimal dict would drift out of shape
# as the schema grows and start failing for the wrong reason, which is how a guard
# test quietly stops testing its guard.
# ---------------------------------------------------------------------------


def _corrupt(mutate):
    """Deep-copy the committed contracts, apply one corruption, return the result."""
    contracts = copy.deepcopy(load_observable_contracts())
    mutate(contracts)
    return contracts


def _duplicate_dataset_id(contracts):
    contracts["datasets"].append(copy.deepcopy(contracts["datasets"][0]))


def _duplicate_citation_key(contracts):
    papers = contracts["bibliography"]["papers"]
    clone = copy.deepcopy(papers[0])
    clone["inspire_id"] = max(int(p["inspire_id"]) for p in papers) + 1
    papers.append(clone)


def _duplicate_inspire_id(contracts):
    papers = contracts["bibliography"]["papers"]
    clone = copy.deepcopy(papers[0])
    clone["citation_key"] = clone["citation_key"] + "_clone"
    papers.append(clone)


def _unresolved_citation_key(contracts):
    for record in contracts["datasets"]:
        if record["citation_keys"]:
            record["citation_keys"] = list(record["citation_keys"]) + ["NoSuchPaper2099"]
            return
    raise AssertionError("no dataset carries a citation key; fixture assumption broken")


def _selects_more_rows_than_exist(contracts):
    record = contracts["datasets"][0]
    record["source_rows"] = 10
    record["selected_rows"] = 11
    record["selectable"] = True


def _selectable_disagrees_with_row_count(contracts):
    for record in contracts["datasets"]:
        if int(record["selected_rows"]) > 0:
            record["selectable"] = False
            return
    raise AssertionError("no dataset selects any row; fixture assumption broken")


def _mode_references_unknown_dataset(contracts):
    mode = next(iter(contracts["full_closure_modes"].values()))
    mode["dataset_ids"] = list(mode["dataset_ids"]) + ["definitely_not_a_dataset"]


def _mode_repeats_a_dataset(contracts):
    mode = next(iter(contracts["full_closure_modes"].values()))
    ids = list(mode["dataset_ids"])
    mode["dataset_ids"] = ids + [ids[0]]


def _reuses_a_doi_across_two_papers(contracts):
    papers = contracts["bibliography"]["papers"]
    with_doi = [paper for paper in papers if paper.get("doi")]
    if len(with_doi) < 2:
        raise AssertionError("fewer than two papers carry a doi; fixture assumption broken")
    # Assign, do not clone: a cloned paper would trip the duplicate-citation-key
    # guard (which runs first) and this case would silently test that instead.
    with_doi[1]["doi"] = with_doi[0]["doi"]


def _inspire_ids_disagree_with_citation_keys(contracts):
    for record in contracts["datasets"]:
        if record["citation_keys"] and record.get("inspire_ids"):
            record["inspire_ids"] = []
            return
    raise AssertionError("no dataset carries both fields; fixture assumption broken")


def _physics_record_keeps_an_unresolved_marker(contracts):
    for record in contracts["datasets"]:
        if record["classification"] == "physics":
            record["operator"]["nuclear"] = "unknown"
            return
    raise AssertionError("no physics dataset in the table; fixture assumption broken")


def _mode_selects_a_gated_dataset(contracts):
    gated = next(
        record for record in contracts["datasets"] if not record["selectable"]
    )
    mode = next(iter(contracts["full_closure_modes"].values()))
    # Adding a genuinely gated id, rather than flipping a selected record's
    # `selectable`, keeps this case off the selectable/selected_rows guard in the
    # dataset loop -- which runs earlier and would otherwise fire first.
    mode["dataset_ids"] = list(mode["dataset_ids"]) + [str(gated["id"])]


def _mode_rejects_the_classification(contracts):
    mode = next(iter(contracts["full_closure_modes"].values()))
    outside = next(
        value
        for value in ("reader_only", "not_a_classification")
        if value not in set(mode["classifications"])
    )
    by_id = {str(record["id"]): record for record in contracts["datasets"]}
    # Reclassify a dataset the mode already selects, leaving `selectable` alone so
    # the gated-dataset guard one line earlier stays quiet.  Every *currently*
    # selectable record has a classification the modes accept, so there is no
    # unmodified dataset this case could reach instead.
    by_id[str(mode["dataset_ids"][0])]["classification"] = outside


@pytest.mark.parametrize(
    "mutate, expected",
    [
        (_duplicate_dataset_id, "duplicate dataset ids"),
        (_duplicate_citation_key, "duplicate citation keys"),
        (_duplicate_inspire_id, "duplicate INSPIRE control numbers"),
        (_unresolved_citation_key, "unresolved citation keys"),
        (_selects_more_rows_than_exist, "of only"),
        (_selectable_disagrees_with_row_count, "selectable must equal"),
        (_mode_references_unknown_dataset, "references unknown dataset"),
        (_mode_repeats_a_dataset, "repeats a dataset id"),
        (_reuses_a_doi_across_two_papers, "reuses doi"),
        (_inspire_ids_disagree_with_citation_keys, "INSPIRE ids disagree"),
        (_physics_record_keeps_an_unresolved_marker, "unresolved marker"),
        (_mode_selects_a_gated_dataset, "selects gated dataset"),
        (_mode_rejects_the_classification, "rejects the classification"),
    ],
    ids=[
        "duplicate_dataset_id", "duplicate_citation_key", "duplicate_inspire_id",
        "unresolved_citation_key", "selects_more_rows_than_exist",
        "selectable_disagrees_with_row_count", "mode_references_unknown_dataset",
        "mode_repeats_a_dataset", "reuses_a_doi_across_two_papers",
        "inspire_ids_disagree_with_citation_keys",
        "physics_record_keeps_an_unresolved_marker", "mode_selects_a_gated_dataset",
        "mode_rejects_the_classification",
    ],
)
def test_each_contract_invariant_is_actually_enforced(mutate, expected):
    """Every ``ContractError`` branch in ``validate_observable_contracts`` fires.

    Oracle ``F1``; constrains no numerics.  What it establishes is that the guards
    protecting every other test in this file are real -- eight ``raise`` branches
    (``contracts.py:65-140``) that, before this test, were executed by nothing in the
    repository.

    **Why this is not redundant with the completeness tests above.** Those assert the
    invariants hold on the *committed* table, which the loader has already guaranteed
    by raising -- so they can neither fail nor pass informatively.  This one asserts
    the loader would *notice*.  A validator nobody has watched reject anything is
    indistinguishable from one that returns ``None`` unconditionally, which is exactly
    what ``validate_observable_contracts`` does on success.

    Each case corrupts a deep copy in exactly one way, so a failure names one branch
    rather than "something is wrong with the table".  The message is matched, not just
    the exception type: several of these branches raise the same ``ContractError``, and
    matching only the type would let a corruption trip the wrong guard and still pass --
    which would silently merge two independent checks into one.

    Two corruptions are constructed so they trip *only* their target guard: the
    duplicate-citation-key clone gets a fresh ``inspire_id`` (or it would trip the
    INSPIRE guard first), and the duplicate-INSPIRE clone gets a fresh citation key.
    That ordering sensitivity is itself a finding -- the guards are not independent, and
    a naive duplicate would have tested whichever runs first.

    Extended 2026-08-13 from 8 cases to 13, closing the five ``raise`` branches the
    first pass left unreached (``contracts.py:79`` doi/arxiv reuse, ``109``
    inspire/citation disagreement, ``128`` forbidden physics marker, ``143`` a mode
    selecting a gated dataset, ``147`` a mode rejecting a classification).  Same
    ordering discipline: ``_reuses_a_doi_across_two_papers`` assigns rather than
    clones so it does not trip the duplicate-key guard, ``_mode_selects_a_gated_dataset``
    appends an already-gated id rather than flipping ``selectable`` on a selected one
    (which the dataset-loop guard would catch first), and
    ``_mode_rejects_the_classification`` leaves ``selectable`` alone so the gated guard
    one line above it stays quiet.  With all thirteen present,
    ``validate_observable_contracts`` has no unexercised ``raise`` left.
    """
    with pytest.raises(ContractError, match=expected):
        validate_observable_contracts(_corrupt(mutate))


def test_the_committed_contracts_pass_the_same_validator():
    """The control: an unmodified table raises nothing.

    Without this, every case above would pass if ``validate_observable_contracts``
    raised unconditionally -- eight tests green on a validator that rejects everything,
    the mirror image of the flaw they were written to fix.
    """
    validate_observable_contracts(copy.deepcopy(load_observable_contracts()))


@pytest.mark.parametrize(
    "content, expected",
    [
        (None, "cannot load observable contracts"),
        ("datasets: [ unclosed", "cannot load observable contracts"),
        ("schema_version: 1\n", "observable contract schema error"),
    ],
    ids=["missing_file", "malformed_yaml", "schema_invalid"],
)
def test_the_loader_reports_unreadable_and_schema_invalid_contract_files(
    tmp_path, content, expected
):
    """``load_observable_contracts(path=...)``'s two failure branches both fire.

    Oracle ``F1``; no numerics.  ``contracts.py:49-50`` (``OSError``/``YAMLError`` ->
    "cannot load observable contracts") and ``53-55`` (``jsonschema.ValidationError``
    -> "observable contract schema error at <location>") were listed as uncovered
    alongside the cross-field guards above, and are the layer *underneath* them: if
    the schema check silently stopped raising, every schema-only invariant this file
    leans on (see the entry's "physics-metadata loop" note -- 3 of its 5 checks are
    the schema's job, not the test's) would become unenforced with nothing noticing.

    ``schema_version: 1`` alone is well-formed YAML and a valid mapping, so it can
    only fail on the schema's ``required`` list -- it reaches the second branch
    without touching the first.  The message, not just ``ContractError``, is matched:
    both branches raise the same class, and matching the type alone would let a
    malformed file report itself as a schema error or vice versa.  The control that
    keeps this honest is the whole rest of the file, every test of which loads the
    committed contracts through this same function without raising.
    """
    path = tmp_path / "contracts.yaml"
    if content is not None:
        path.write_text(content, encoding="utf-8")
    with pytest.raises(ContractError, match=expected):
        load_observable_contracts(path)


# ---------------------------------------------------------------------------
# The selector and annotation layer, added 2026-08-13.
#
# ``annotate_manifest`` is what turns "a missing citation or an ambiguous selector"
# into a generation-time error (its own docstring).  Until now nothing had ever
# watched it do that: every call in this file passes a real manifest whose records
# all match exactly one contract, so the ``len(matches) != 1`` raise had no test,
# and the ``commondata_name`` selector -- used by 22 of the 52 dataset records, i.e.
# every EW/NNPDF extension candidate -- had never been evaluated against any record
# at all, because the committed manifests carry no ``"datasets"`` section for it to
# match.  Both are exercised here on a synthetic manifest rather than by waiting for
# a candidate to be promoted.
# ---------------------------------------------------------------------------


def _commondata_selected_contract(contracts):
    """Return the first contract that selects by ``commondata_name``, or fail loudly."""
    for record in contracts["datasets"]:
        if "commondata_name" in record["selector"]:
            return record
    raise AssertionError("no contract selects by commondata_name; fixture assumption broken")


@pytest.mark.parametrize("alias", ["commondata_name", "setname", "source_id"])
def test_the_commondata_name_selector_matches_through_its_whole_fallback_chain(alias):
    """A ``"datasets"`` record matches its contract under all three name spellings.

    Oracle ``F1``: selector routing, no numerics.  ``_selector_matches``
    (``contracts.py:248-251``) reads ``record.get("commondata_name",
    record.get("setname", record.get("source_id")))`` -- a three-deep fallback chain
    that, per the coverage index, no test in the suite had ever entered.  Each
    parametrized case supplies the name under exactly one of the three keys, so a
    dropped link in the chain fails one case and leaves the others green, naming the
    broken link instead of reporting "selectors are broken".

    The negative half is what makes this more than a smoke test: the same record
    under a *wrong* name must match zero contracts, so a ``_selector_matches`` that
    fell through to ``return True`` whenever the key was absent -- the natural
    failure of a fallback chain -- would fail here even though every positive case
    still passed.  The section is checked too: the identical record under
    ``section="exp"`` matches nothing, since ``_selector_matches``'s first line
    compares sections before looking at any name.
    """
    contracts = load_observable_contracts()
    contract = _commondata_selected_contract(contracts)
    name = contract["selector"]["commondata_name"]

    matches = matching_contracts(contracts, "datasets", {alias: name})
    assert [record["id"] for record in matches] == [contract["id"]]
    # Negative: an unknown name matches nothing.  Without this, a selector that
    # ignored the name entirely would pass every positive case above.
    assert matching_contracts(contracts, "datasets", {alias: "not_a_commondata_set"}) == []
    # And the section gate still applies to the very same record.
    assert matching_contracts(contracts, "exp", {alias: name}) == []


def test_annotate_manifest_refuses_a_datasets_record_matching_other_than_one_contract():
    """The ambiguous/zero-match raise fires, and the exactly-one case annotates.

    Oracle ``F1``.  ``annotate_manifest``'s ``len(matches) != 1`` branch
    (``contracts.py:287-291``) is the mechanism its own docstring credits with making
    an ambiguous selector "a generation-time error instead of a reporting-time
    warning", and nothing had ever triggered it.  Both sides of ``!= 1`` are covered:
    zero matches (an unknown ``commondata_name``) and two matches (a second contract
    cloned onto the same selector), each matched on the reported *count* in the
    message rather than on ``ContractError`` alone -- the two arms raise the same
    class from the same line, and a guard that reported "2" when it meant "0" would
    otherwise be invisible.

    The third case is the control, and it doubles as the first end-to-end exercise of
    the ``"datasets"`` section in ``annotate_manifest``'s *default* ``sections`` tuple
    (``contracts.py:274``) -- the landing zone for a promoted EW/NNPDF candidate,
    which today's committed manifests never populate.  It asserts the annotation was
    actually written and carries the matched contract's own id and citations, so the
    guard cannot be satisfied by a function that raises on everything, nor by one
    that walks the section without annotating it.
    """
    contracts = load_observable_contracts()
    contract = _commondata_selected_contract(contracts)
    name = contract["selector"]["commondata_name"]

    with pytest.raises(ContractError, match="matches 0 contracts"):
        annotate_manifest(
            {"datasets": [{"name": "orphan", "commondata_name": "not_a_commondata_set"}]},
            contracts=contracts,
        )

    ambiguous = copy.deepcopy(contracts)
    clone = copy.deepcopy(contract)
    clone["id"] = str(contract["id"]) + ".clone"
    ambiguous["datasets"].append(clone)
    with pytest.raises(ContractError, match="matches 2 contracts"):
        annotate_manifest(
            {"datasets": [{"name": "ambiguous", "commondata_name": name}]},
            contracts=ambiguous,
        )

    # Control + the "datasets" section end to end: exactly one match annotates.
    annotated = annotate_manifest(
        {"datasets": [{"name": "promoted", "commondata_name": name}]},
        contracts=contracts,
    )
    record = annotated["datasets"][0]
    assert record["contract_id"] == contract["id"]
    assert record["classification"] == contract["classification"]
    assert record["citation_keys"] == list(contract["citation_keys"])
    assert record["provenance"]["contract_id"] == contract["id"]


def test_contract_artifact_provenance_digests_the_two_files_it_names(tmp_path):
    """The stamped sha256 digests are of the real contract and bibliography bytes.

    ``contract_artifact_provenance`` is ``__all__``-exported and 0% covered, yet both
    closure suites' ``generate.py`` and ``closure_audit.py`` call it to bake these
    digests into every generated manifest's provenance record -- a provenance stamp
    nobody had ever checked stamps the right bytes.

    Oracle ``A1`` for the digests: ``hashlib.sha256`` over bytes this test reads
    itself, so the expected value comes from the file rather than from the function.
    That alone would still pass if the function hashed the wrong file, so the second
    half is the load-bearing one: pointed at a scratch ``root`` holding *different*
    contract and bibliography bytes, both digests must change, and each must equal
    the digest of the scratch file with the corresponding name.  A function returning
    a constant, or reading the repository copy regardless of ``root``, fails there.
    The bibliography path is taken from ``contracts["bibliography"]["path"]``, which
    is the one thing that decides *which* second file gets stamped.
    """
    contracts = load_observable_contracts()
    contract_path = ROOT / "observable_contracts.yaml"
    bibliography_path = ROOT / contracts["bibliography"]["path"]

    provenance = contract_artifact_provenance(contracts)
    assert provenance["observable_contracts"] == contract_path.name
    assert provenance["bibliography"] == bibliography_path.name
    assert provenance["observable_contracts_sha256"] == hashlib.sha256(
        contract_path.read_bytes()
    ).hexdigest()
    assert provenance["bibliography_sha256"] == hashlib.sha256(
        bibliography_path.read_bytes()
    ).hexdigest()

    # Different bytes under a different root must give different digests -- the half
    # that a constant-returning implementation would fail.
    (tmp_path / "observable_contracts.yaml").write_bytes(b"not the real contracts\n")
    (tmp_path / bibliography_path.name).write_bytes(b"not the real bibliography\n")
    scratch = contract_artifact_provenance(contracts, root=tmp_path)
    assert scratch["observable_contracts_sha256"] != provenance["observable_contracts_sha256"]
    assert scratch["bibliography_sha256"] != provenance["bibliography_sha256"]
    assert scratch["observable_contracts_sha256"] == hashlib.sha256(
        b"not the real contracts\n"
    ).hexdigest()
    assert scratch["bibliography_sha256"] == hashlib.sha256(
        b"not the real bibliography\n"
    ).hexdigest()


def test_lattice_selected_rows_reconcile_with_the_generated_full_manifest():
    """The lattice half of the ``exp``/``dy`` reconciliation, which had no equivalent.

    Oracle ``A3``: the count comes from the committed, generated manifest;
    ``selected_rows`` comes from the yaml.  The sibling completeness test does check
    the lattice totals (``== 234``, ``all(... == 18)``), but against *independently
    hardcoded literals* -- so an edit that moved a lattice contract's
    ``selected_rows`` away from what generation actually emits was caught nowhere in
    this file, which is precisely the drift
    ``test_selected_point_counts_reconcile_with_generated_full_manifest`` exists to
    catch for ``exp``/``dy``.

    The lattice unit differs from ``exp``/``dy``'s and the assertion follows it: one
    lattice contract covers a whole ensemble, so its ``selected_rows`` (18) is the
    number of *manifest records* selected by that contract, not the row count of any
    one data file.  ``matching_contracts`` is what partitions the records, and
    ``len(matches) == 1`` is asserted first, so an ambiguous ``name_regex`` cannot
    quietly inflate one ensemble's tally by stealing another's records.  Both
    committed suites are checked; the sum is asserted too, so a contract that matched
    nothing would fail here rather than being skipped by an empty ``Counter``.
    """
    contracts = load_observable_contracts()
    by_id = contract_index(contracts)
    lattice_ids = sorted(
        dataset_id for dataset_id in by_id if dataset_id.startswith("lattice.")
    )
    assert lattice_ids, "no lattice contracts in the table; fixture assumption broken"

    for suite in ("closure_JAM_truth", "closure_NNPDF_truth"):
        manifest = _manifest(suite)
        seen = Counter()
        for record in manifest["lattice"]:
            matches = matching_contracts(contracts, "lattice", record)
            assert len(matches) == 1
            seen[str(matches[0]["id"])] += 1
        for dataset_id in lattice_ids:
            assert seen[dataset_id] == by_id[dataset_id]["selected_rows"]
        assert sum(seen.values()) == sum(
            by_id[dataset_id]["selected_rows"] for dataset_id in lattice_ids
        )
